language: java
install: true

jdk:
  - oraclejdk11


before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  -  gradle wrapper --gradle-version 5.0 --distribution-type all
  - ./gradlew test
  - ./gradlew build 

